name: flutter_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  build_runner: ^2.13.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.4
  json_annotation: ^4.11.0
  json_serializable: ^6.13.1
  freezed: ^3.2.5
  freezed_annotation: ^3.1.0
  dio: ^5.9.2
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.9.2
  retrofit_generator: ^10.2.3
  flutter_bloc: ^9.1.1
  bloc: ^9.2.0
  get_it: ^9.2.1
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/articles/
    - assets/svgs/

  fonts:
    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend/static/Lexend-Thin.ttf
          weight: 100
        - asset: assets/fonts/Lexend/static/Lexend-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Lexend/static/Lexend-Light.ttf
          weight: 300
        - asset: assets/fonts/Lexend/static/Lexend-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lexend/static/Lexend-Medium.ttf
          weight: 500
        - asset: assets/fonts/Lexend/static/Lexend-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Lexend/static/Lexend-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lexend/static/Lexend-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Lexend/static/Lexend-Black.ttf
          weight: 900
    - family: Newsreader
      fonts:
        - asset: assets/fonts/new_sreader/static/Newsreader_9pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/new_sreader/static/Newsreader_14pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/new_sreader/static/Newsreader_14pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/new_sreader/static/Newsreader_14pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/new_sreader/static/Newsreader_14pt-Italic.ttf
          style: italic
    - family: PublicSans
      fonts:
        - asset: assets/fonts/PublicSans/PublicSans-VariableFont_wght.ttf
        - asset: assets/fonts/PublicSans/PublicSans-Italic-VariableFont_wght.ttf
          style: italic
